# Generated by Django 5.0.4 on 2024-05-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_user_permissions',
        ),
    ]
