# Generated by Django 5.0.4 on 2024-05-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_employee_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
