# Generated by Django 5.0.4 on 2024-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age_years',
            field=models.IntegerField(null=True),
        ),
    ]
