# Generated by Django 5.0.4 on 2024-05-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_attendance_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
