# Generated by Django 5.0.4 on 2024-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.BooleanField(),
        ),
    ]
