# Generated by Django 5.0.4 on 2024-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
