name: Build and deploy Python app to Azure Web App - tracktron

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Use a supported Python version (e.g., 3.6, 3.7, 3.8, 3.9)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application
        run: |
          # Create a ZIP archive excluding unnecessary files (e.g., virtual environment)
          zip -r deployment-package.zip .

      - name: Upload deployment package
        uses: actions/upload-artifact@v2
        with:
          name: deployment-package
          path: deployment-package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v2
        with:
          name: deployment-package
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tracktron'
          slot-name: 'Production'
          publish-profile: ${{ AZURE_CREDENTIALS.AZUREAPPSERVICE_PUBLISHPROFILE }}
